/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThanksReplyTokenRouteImport } from './routes/thanks.$replyToken'
import { Route as RLinkIdRouteImport } from './routes/r.$linkId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksReplyTokenRoute = ThanksReplyTokenRouteImport.update({
  id: '/thanks/$replyToken',
  path: '/thanks/$replyToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RLinkIdRoute = RLinkIdRouteImport.update({
  id: '/r/$linkId',
  path: '/r/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/privacy': typeof PrivacyRoute
  '/r/$linkId': typeof RLinkIdRoute
  '/thanks/$replyToken': typeof ThanksReplyTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/privacy': typeof PrivacyRoute
  '/r/$linkId': typeof RLinkIdRoute
  '/thanks/$replyToken': typeof ThanksReplyTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/privacy': typeof PrivacyRoute
  '/r/$linkId': typeof RLinkIdRoute
  '/thanks/$replyToken': typeof ThanksReplyTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inbox' | '/privacy' | '/r/$linkId' | '/thanks/$replyToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inbox' | '/privacy' | '/r/$linkId' | '/thanks/$replyToken'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/privacy'
    | '/r/$linkId'
    | '/thanks/$replyToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  PrivacyRoute: typeof PrivacyRoute
  RLinkIdRoute: typeof RLinkIdRoute
  ThanksReplyTokenRoute: typeof ThanksReplyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks/$replyToken': {
      id: '/thanks/$replyToken'
      path: '/thanks/$replyToken'
      fullPath: '/thanks/$replyToken'
      preLoaderRoute: typeof ThanksReplyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$linkId': {
      id: '/r/$linkId'
      path: '/r/$linkId'
      fullPath: '/r/$linkId'
      preLoaderRoute: typeof RLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  PrivacyRoute: PrivacyRoute,
  RLinkIdRoute: RLinkIdRoute,
  ThanksReplyTokenRoute: ThanksReplyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
